In [26]:
import pandas as pd
import random as rd
import numpy as np 
import datetime
import matplotlib.pyplot as plt

In [27]:
df = pd.read_csv('music_genre.csv')
df.head()

,instance_id,artist_name,track_name,popularity,acousticness,danceability,duration_ms,energy,instrumentalness,key,liveness,loudness,mode,speechiness,tempo,obtained_date,valence,music_genre
0,32894.0,Röyksopp,Röyksopp's Night Out,27.0,0.00468,0.652,-1.0,0.941,0.79200,A#,0.115,-5.201,Minor,0.0748,100.889,4-Apr,0.759,Electronic
1,46652.0,Thievery Corporation,The Shining Path,31.0,0.01270,0.622,218293.0,0.890,0.95000,D,0.124,-7.043,Minor,0.0300,115.00200000000001,4-Apr,0.531,Electronic
2,30097.0,Dillon Francis,Hurricane,28.0,0.00306,0.620,215613.0,0.755,0.01180,G#,0.534,-4.617,Major,0.0345,127.994,4-Apr,0.333,Electronic
3,62177.0,Dubloadz,Nitro,34.0,0.02540,0.774,166875.0,0.700,0.00253,C#,0.157,-4.498,Major,0.2390,128.014,4-Apr,0.270,Electronic
4,24907.0,What So Not,Divide & Conquer,32.0,0.00465,0.638,222369.0,0.587,0.90900,F#,0.157,-6.266,Major,0.0413,145.036,4-Apr,0.323,Electronic

In [28]:
#We get rid of the useless parameters 
df = df.drop(['acousticness','instrumentalness','key','liveness','loudness','mode','speechiness','obtained_date','valence'], axis=1)
df = df.dropna()

# instance_id should be an integer
df["instance_id"] = [int(x) for x in df["instance_id"]]

#modifie the df["danceability"] to be in %
df["danceability"] = round(df["danceability"]*100)

#drop the  line if df["duration_ms"] is Nan
df = df[df["duration_ms"].notnull()]
df["duration_ms"] = df["duration_ms"].apply(lambda x: f'{round(x/1000)//60}:{round(x/1000)%60}')

#modifie the df["energy"] to be in %
df["energy"] = round(df["energy"]*100)

#replace all ? by 0 in the df['tempo']
df['tempo'] = df['tempo'].replace('?',0)
#convert the tempo to float and round it
df['tempo'] = df['tempo'].apply(lambda x: round(float(x)))
df.head(10)

,instance_id,artist_name,track_name,popularity,danceability,duration_ms,energy,tempo,music_genre
0,32894,Röyksopp,Röyksopp's Night Out,27.0,65.0,0:0,94.0,101,Electronic
1,46652,Thievery Corporation,The Shining Path,31.0,62.0,3:38,89.0,115,Electronic
2,30097,Dillon Francis,Hurricane,28.0,62.0,3:36,76.0,128,Electronic
3,62177,Dubloadz,Nitro,34.0,77.0,2:47,70.0,128,Electronic
4,24907,What So Not,Divide & Conquer,32.0,64.0,3:42,59.0,145,Electronic
5,89064,Axel Boman,Hello,47.0,76.0,8:39,73.0,0,Electronic
6,43760,Jordan Comolli,Clash,46.0,57.0,3:34,80.0,150,Electronic
7,30738,Hraach,Delirio,43.0,81.0,6:56,71.0,120,Electronic
8,84950,Kayzo,NEVER ALONE,39.0,51.0,4:53,92.0,150,Electronic
9,56950,Shlump,Lazer Beam,22.0,58.0,3:25,73.0,140,Electronic

In [29]:
# In order to recommend something to an user, we have to know the user. 
# We have to gather data on the user like what were his last searches when talking to our chatbot


# Then see for each column : artist, popularity, danceability, tempo and music genre if one of them is a trend between his searches

# In our code we must gather the data on the searches of the user

In [30]:
# Create a dataframe_user with a user_id and the names of all songs he looked for
# The user is identified by his twitch account in our dataframe

data = {'username':[], 
        'instance_id':[],	
        'artist_name':[],	
        'track_name':[],	
        'popularity':[],	
        'danceability':[],	
        'duration_ms':[],	
        'energy':[],	
        'tempo':[],	
        'music_genre':[], 
        'rating':[]}
        
df_users = pd.DataFrame(data)   
print(df_users)

Empty DataFrame
Columns: [username, instance_id, artist_name, track_name, popularity, danceability, duration_ms, energy, tempo, music_genre, rating]
Index: []

In [31]:
df_users = {'username': ['ladehkos','benjamin#2222'], 
            'instance_id':['123','456'],	
            'artist_name':['NAPS','The Chainsmokers'],	
            'track_name':['La kiffance','Hurricane'],	
            'popularity':[99,99],	
            'danceability':[99,67],	
            'duration_ms':['3:12','2:34'],	
            'energy': [99, 72],	
            'tempo':['140', '120'],	
            'music_genre':['Electronic', 'Samba']}

In [32]:
#Add a new line in the dataset

new_row = ['benjamin#2222', '325', 'Oui', 'Oui', 99, 74, '5:32', 12, '230', 'Diverse']

df_users.loc[len(df_users)] = new_row

#df.reset_index(drop=True)

AttributeError: 'dict' object has no attribute 'loc'

In [ ]:
#The dataframe with all the tracks searched by a specific user

benj = df_users[df_users['username'] == 'benjamin#2222']
benj

,username,instance_id,artist_name,track_name,popularity,danceability,duration_ms,energy,tempo,music_genre
0,benjamin#2222,325,Oui,Oui,99,74,5:32,12,230,Diverse

In [ ]:
# On calcule la taille de ce subdataframe pour voir s'il est supérieur à 3 
# dans ce cas on recommande la chanson la plus populaire de l'artiste (non présente dans le dataset) au username

df_users[df_users['username']==@username][df_users['artist_name']==@artist]
df_users[df_users['track_name']=='La kiffance'][df_users['artist_name']=='NAPS']#example

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,username,instance_id,artist_name,track_name,popularity,danceability,duration_ms,energy,tempo,music_genre
0,ladehkos,123,NAPS,La kiffance,99,99,3:12,99,140,Electronic

In [ ]:
#faire une fonction cosine avec les différentes musiques du tableau
#pour ce faire on utilise un one-hot-encoding sur les music genre 
# puis utiliser les variables quantifiables